name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMVER_GH_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push operator image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/henrywhitaker3/crunchy-users:latest
            ghcr.io/henrywhitaker3/crunchy-users:${{ github.ref_name }}
          build-args: |
            VERSION=${{ github.ref_name }}

      - uses: actions/checkout@v5
        with:
          ref: main
      - name: Get chart version
        run: |
          CHART_VERSION=$(cat chart/Chart.yaml | grep -Eo ": [0-9]+\.[0-9]+\.[0-9]+$" | cut -d' ' -f 2 | awk -F. -v OFS=. '{$NF += 1 ; print}')
          echo "CHART_VERSION=${CHART_VERSION}" >> $GITHUB_ENV
      - name: Update chart AppVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.appVersion = "${{ github.ref_name }}"' 'chart/Chart.yaml'
      - name: Update chart Version
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.version = "${{ env.CHART_VERSION }}"' 'chart/Chart.yaml'
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(chart): update version to ${{ github.ref_name }}"
      - name: Push chart
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: crunchy-users-helm
          repository: henrywhitaker3
          tag: "${{ env.CHART_VERSION }}"
          path: chart
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true'
