name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMVER_GH_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push operator image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          push: true
          tags: |
            ghcr.io/henrywhitaker3/crunchy-users:latest
            ghcr.io/henrywhitaker3/crunchy-users:${{ github.ref_name }}
          build-args: |
            VERSION=${{ github.ref_name }}

      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          ref: main
      - name: Get chart version
        run: |
          CHART_VERSION=$(cat chart/Chart.yaml | grep -Eo ": [0-9]+\.[0-9]+\.[0-9]+$" | cut -d' ' -f 2 | awk -F. -v OFS=. '{$NF += 1 ; print}')
          echo "CHART_VERSION=${CHART_VERSION}" >> $GITHUB_ENV
      - name: Update chart AppVersion
        uses: mikefarah/yq@8b5af0694bb82b41d4ae180fac9972029066f90a # master
        with:
          cmd: yq -i '.appVersion = "${{ github.ref_name }}"' 'chart/Chart.yaml'
      - name: Update chart Version
        uses: mikefarah/yq@8b5af0694bb82b41d4ae180fac9972029066f90a # master
        with:
          cmd: yq -i '.version = "${{ env.CHART_VERSION }}"' 'chart/Chart.yaml'
      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          commit_message: "chore(chart): update version to ${{ github.ref_name }}"
      - name: Push chart
        uses: appany/helm-oci-chart-releaser@d94988c92bed2e09c6113981f15f8bb495d10943 # v0.5.0
        with:
          name: crunchy-users-helm
          repository: henrywhitaker3
          tag: "${{ env.CHART_VERSION }}"
          path: chart
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true'
